const $=id=>document.getElementById(id);let state,editing=false,selected='baseline',lastRun='';
async function api(url,body){const r=await fetch('/api/optimization'+url,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const v=await r.json();if(!r.ok)throw Error(v.error?.message||'Request failed');return v;}
function text(parent,tag,value,cls){const n=document.createElement(tag);n.textContent=value;if(cls)n.className=cls;parent.append(n);return n;}
function fill(name){const p=state.profiles.find(x=>x.name===name)||state.active;selected=name;$('quote_hints').checked=!!p.quote_hints;for(const k of ['temperature','max_tokens','context_window','max_context_chars','prompt_template'])$(k).value=p[k];editing=true;}
function paint(v){state=v;for(const id of ['apply','compare','baseline','optimized'])$(id).disabled=v.busy||v.context_locked;$('progress').textContent=v.progress;$('runtime').textContent=v.runtime?`Verified ${v.runtime.actual_context_tokens.toLocaleString()} tokens · owned PID ${v.runtime.pid}`:'Context verification pending';$('active').textContent=v.active?`Active: ${v.active.name}`:'Default: baseline pending review';if(v.error)$('message').textContent=v.error;$('quant').textContent=(v.quantization.inventory_status||v.quantization.decision)==='ONLY_ONE_COMPARABLE_QUANT_AVAILABLE'?'Only one same-model quantization is available. Its actual file is recorded; no invented A/B result.':'Same-model quantizations are available.';$('files').replaceChildren();v.quantization.variants.forEach(f=>text($('files'),'div',`${f.name} · ${(f.size_bytes/1e9).toFixed(2)} GB`,'file'));
 const c=v.comparison;if(!c)return;const signature=JSON.stringify([c.run_id,c.baseline.length,c.optimized.length,c.quality_review,c.selected_profile,c.completed_at,c.error]);if(signature===lastRun)return;lastRun=signature;$('metrics').replaceChildren();for(const [label,key,unit,scale] of [['Mean latency','mean_latency_ms','s',1000],['Mean CPU time','mean_cpu_seconds','s',1],['Peak host RAM','peak_ram_bytes','GiB',1073741824],['Truncated answers','length_count','',1]]){const n=text($('metrics'),'div','','metric');text(n,'small',label);text(n,'strong',`${c.baseline_summary? (c.baseline_summary[key]/scale).toFixed(2):'—'} → ${c.optimized_summary?(c.optimized_summary[key]/scale).toFixed(2):'—'} ${unit}`);text(n,'small','baseline → candidate');}
 $('review').textContent=`Quality: ${c.quality_review}. Selected default: ${c.selected_profile?.name||c.selected_profile}. ${c.selection_reason}`;$('answers').replaceChildren();const ids=[...new Set([...c.baseline,...c.optimized].map(r=>r.id))];for(const id of ids){const row=c.baseline.find(r=>r.id===id)||c.optimized.find(r=>r.id===id);const d=text($('answers'),'details','');text(d,'summary',row.question);text(d,'p','Expected: '+row.expected_facts.join('; '),'muted');const pair=text(d,'div','','pair');for(const name of ['baseline','optimized']){const r=c[name].find(x=>x.id===id),n=text(pair,'div','','answer');text(n,'h3',name==='baseline'?'Before':'After');if(r){text(n,'p',r.answer.text);text(n,'p',`Citation structure: ${r.citation_check.status}. Semantic grade: ${r.quality}`,'muted');text(n,'p',`${(r.resources.wall_ms/1000).toFixed(2)} s · finish: ${r.answer.finish_reason} · context: ${r.actual_context_tokens} tokens · quality: ${r.quality}`,'muted');const ev=text(n,'details','');text(ev,'summary','Supplied source excerpts');for(const source of r.sources)text(ev,'p',`[${source.index}] ${source.quote}`);}else text(n,'p','Not run yet');}}
 if(c.truncation_probe){const d=text($('answers'),'details','');text(d,'summary',`Controlled truncation · max output 8 tokens · finish: ${c.truncation_probe.answer.finish_reason}`);text(d,'p',c.truncation_probe.answer.text);}
}
$('baseline').onclick=()=>fill('baseline');$('optimized').onclick=()=>fill('optimized');$('apply').onclick=async()=>{const p={name:selected,quote_hints:$('quote_hints').checked,prompt_template:$('prompt_template').value};for(const k of ['temperature','max_tokens','context_window','max_context_chars'])p[k]=Number($(k).value);$('apply').disabled=true;$('message').textContent='Loading / verifying actual model context…';try{const v=await api('/profile',p);$('message').textContent=`Applied: ${v.runtime.actual_context_tokens} actual model tokens`;paint(await api(''));}catch(e){$('message').textContent=e.message;$('apply').disabled=false;}};
$('compare').onclick=async()=>{try{await api('/compare',{});paint(await api(''));}catch(e){$('message').textContent=e.message;}};
async function refresh(){try{const v=await api('');paint(v);if(!editing)fill(v.active?.name||'baseline');}catch(e){$('message').textContent=e.message;}}refresh();setInterval(refresh,2000);

for(const id of ["temperature","max_tokens","context_window","max_context_chars","prompt_template","quote_hints"])$(id).addEventListener("input",()=>{selected="custom";editing=true;});
